### ISSUE TITLE
Avoid creating duplicate policies

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#691] opened 2023-08-13 05:33 UTC
We have tons of duplicate policies
<img width="463" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/4326c910-e335-44ac-a9ee-ab31937a31bf">

**Comment by patrickhanl** [comment] 2023-09-01 15:44
@MaxGhenis 
If you hit the api directly it returns these duplicate values, looks like the app is accurately reflecting the data from the api.

It is possible to de-dupe these on the front end but seems like it would be better to remove from the data source?

Should this get reported as an issue on the api or engine repos?

![api-results](https://github.com/PolicyEngine/policyengine-app/assets/49796873/ddb30e7b-d990-42ce-8352-5202299aea8e)

**Comment by MaxGhenis** [comment] 2023-09-01 15:50
@patrickhanl Good point, I filed https://github.com/PolicyEngine/policyengine-api/issues/726 to clear them out and changed this one to be about avoiding creating duplicates. If that's also an API issue we can transfer it.

**Comment by patrickhanl** [comment] 2023-09-01 19:50
@MaxGhenis @nikhilwoodruff 
Is there any intent for the site user to be able to create policies? There's a method that gets called from fields in the right sidebar and parameter editor that makes a post request with the entered policy that looks like it's causing this:

https://github.com/PolicyEngine/policyengine-app/blob/08d5edb7e8ee657fa68a21676f88b140db058618/src/api/parameters.js#L122C1-L135C2

![post-fields](https://github.com/PolicyEngine/policyengine-app/assets/49796873/3871fc20-f7b1-4964-b0ad-39ea24d9e1da)

Let me know and I can look into fixing this.

**Comment by MaxGhenis** [comment] 2023-09-01 19:53
Yes we let users name reforms. But in some of these cases it's creating a new reform with the same name without user intent.

**Comment by patrickhanl** [comment] 2023-09-01 20:24
Thanks @MaxGhenis, if you can assign this to me I can dig a little deeper to see if this can be handled in the app or in the api

**Comment by MaxGhenis** [comment] 2023-09-26 15:26
Any progress @patrickhanl?

**Comment by patrickhanl** [comment] 2023-09-27 14:34
Hi @MaxGhenis ,

I've been looking into this and I think I see the root cause but I'm still trying to isolate and find a solution that doesn't involve a major rework for how policies are entered and saved. Should have a more detailed update soon.

**Comment by patrickhanl** [comment] 2023-10-15 17:41
Hi @MaxGhenis @nikhilwoodruff 

Wanted to give a quick update, I see 3 things happening related to this:

1. It looks like 2 post calls are made when the user enters a policy name. This is likely an issue with react code for input and post calls.
2. Users can enter policies with the same label causing duplicates even if the parameters have different values. This can be controlled from the frontend by not allowing users to submit policies with an existing label but it might also be good to have dupe control from the API or engine itself.
3. I'm still investigating but it looks like if the user edits parameters (which makes a post call with no label) then enters a label to save the policy, the app makes a bunch of post calls creating multiple policies with the same label. Not sure what is causing this yet.

1 and 2 I can probably submit a fix for, but 3 will require some more investigation.

Also I see there is a site redesign in progress so I wanted to check too before I go too far if there is going to be any refactoring of the input/submission with the redesign.

Let me know and I'll get to work on a PR to try to resolve the first two issues, thanks!

**Comment by MaxGhenis** [comment] 2023-10-15 18:05
Thanks @patrickhanl! The redesign is pretty much independent of the calculator, so you can go ahead with the PR.

**Comment by dotslashbit** [comment] 2024-01-10 05:02
@anth-volk  Is there any progress on this, I'm interested to work on this. Please give any additional information that is required for working on this issue

**Comment by anth-volk** [comment] 2024-01-11 04:16
@dotslashbit There hasn't been any progress on this, but I think we need to do some deeper thinking to clarify what we're aiming to do here. I'm going to do some thinking on this tomorrow and get back to you then.

**Comment by anth-volk** [comment] 2024-01-12 01:55
Flagging @dotslashbit for visibility.

I'm going to take the liberty of dividing this into at least 4 issues, per what Patrick indicated above, plus an additional that I ran into: If you name a policy, then attempt to rename it, click off the policy, and navigate elsewhere, the app completely falls apart. I couldn't even load the home page. I believe Patrick's no. 2 is basically already #972, so I'll just be adding the other three. 

Ultimately, I think that anything we do should likely be temporary, until we're able to redesign the calculator interface and remove some of the inherent limitations of the structure that this interface is built upon.

**Comment by anth-volk** [comment] 2024-01-12 02:02
This issue is now encapsulated in #972, #1165, #1166, and #1167. Closing.

**Closed by anth-volk** 2024-01-12 02:02 UTC

**Comment by MaxGhenis** [comment] 2024-01-25 20:21
It doesn't seem like any of https://github.com/PolicyEngine/policyengine-app/issues/972, https://github.com/PolicyEngine/policyengine-app/issues/1165, https://github.com/PolicyEngine/policyengine-app/issues/1166, and https://github.com/PolicyEngine/policyengine-app/issues/1167 addresses issues 1 and 3 from https://github.com/PolicyEngine/policyengine-app/issues/691#issuecomment-1763457516. Am I missing something?

**Comment by anth-volk** [comment] 2024-01-25 21:36
#1165 is the front-end equivalent of #691, issue 1, in the sense that the two POST calls being made are to create new households. #972 is meant to address #691, issue 2, while #1166 is supposed to be #691, issue 3. Perhaps my descriptions in them lacked clarity; I'm happy to copy over what Patrick said previously

**Comment by MaxGhenis** [comment] 2024-01-25 21:52
>two POST calls being made are to create new households.

Do you mean new policies?

**Comment by anth-volk** [comment] 2024-01-25 22:08
Wow, that is what I meant, no wonder it wasn't clear
