### ISSUE TITLE
Use fixed width font for code demo on homepage

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#215] opened 2023-02-07 15:27 UTC
<img width="264" alt="image" src="https://user-images.githubusercontent.com/6076111/217288106-38386ddb-308a-4f86-83b4-b2294e808d7e.png">

**Comment by mmarvin3** [comment] 2023-04-13 00:23
Need access to Streamlit app, problem may be Streamlit app related.

**Comment by MaxGhenis** [comment] 2023-04-15 00:47
@nikhilwoodruff is this it? https://github.com/PolicyEngine/policyengine-api-demo

**Comment by MaxGhenis** [comment] 2023-11-20 15:44
This is now at the bottom of https://policyengine.org/us/api (font issue remains)

**Comment by MaxGhenis** [comment] 2023-12-27 01:09
I meant within the API Playground Streamlit app. Not sure it's resolved but it's not showing for me.
<img width="1061" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/46e4df8c-3389-4986-b25d-4947851e9bec">

**Comment by abhcs** [comment] 2023-12-27 01:21
The fix was intended for the API demo that you show above. The fix was working locally but streamlit does not seem to be accepting our update to the repository. There have been [issues like this on streamlit](https://discuss.streamlit.io/t/streamlit-app-not-updating-when-github-repositories-are-updated/49349/7) from a quick web search.

**Comment by abhcs** [comment] 2023-12-27 01:24
@nikhilwoodruff Are you aware of any actions that we need to take to ensure that the api-demo repository is read correctly by streamlit?

**Comment by anth-volk** [comment] 2023-12-27 02:33
Just looked into this myself, and it must be deploy-related, as I can run locally without a problem. Perhaps the iframe link changes each time Streamlit re-deploys off the repo?

**Comment by nikhilwoodruff** [comment] 2023-12-27 11:16
Yeah I've found more unexplained issues with Streamlit lately (e.g. with the UK calibration [app](https://policyengine-uk-validation.streamlit.app)), there doesn't seem to be anything in the error logs

**Comment by abhcs** [comment] 2023-12-28 01:52
When I modified the URL to [this](https://policyengine-policyengine-api-demo-app-xy5rgn.streamlit.app), I got a message saying that the app was waking up:

<img width="807" alt="Screenshot 2023-12-27 at 7 42 26 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/6438bb01-1e31-467e-85a9-046a1a5acf06">

Now, I can see the app at the above URL but not on the API page.

**Comment by abhcs** [comment] 2023-12-28 03:43
Closing the issue since the app is visible on the website now.

<img width="640" alt="Screenshot 2023-12-27 at 9 39 19 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/42c8d194-b573-47c2-8f6b-0496e2b9959c">

**Closed by abhcs** 2023-12-28 03:43 UTC
Labels: good first issue

**Comment by MaxGhenis** [comment] 2023-12-28 07:46
Confirming it applies to all three tabs (Python snippet was where the issue was). Thanks!
<img width="396" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/d2377b4e-49a3-4339-a9ab-2fa99b1b4184">
