### ISSUE TITLE
Remove carousel in mobile view

### ISSUE THREAD

**Issue by rachel-lawrie** [PolicyEngine/policyengine-app#1954] opened 2024-08-09 20:30 UTC
Carousel looks weird in mobile view. Redundant with MobileBottomNavButtons. Creates cut-off text as well.

https://www.loom.com/share/da516a7ee6b9447ca3e71f75eb18408c?sid=0cb059cc-547b-4f23-a4b3-39c54c415bbb

**Comment by anth-volk** [comment] 2024-08-09 21:22
Is this a duplicate of #1945?

**Comment by rachel-lawrie** [comment] 2024-08-12 16:07
Duplicate of #1945

**Closed** 2024-08-12 16:07 UTC
