### ISSUE TITLE
Distinguish State vs federal budgetary impacts

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#507] opened 2023-04-29 20:58 UTC
When simulating non-federal regions, we should show in the budgetary impact chart:
* Federal tax revenues
* State tax revenues
* Federal benefit spending

cc @MaxGhenis

**Comment by MaxGhenis** [comment] 2023-04-29 22:09
Duplicate of #501

**Closed** 2023-04-29 22:09 UTC
