### ISSUE TITLE
White screen on policy #8952

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1599] opened 2024-04-12 20:07 UTC
When attempting to load https://policyengine.org/us/policy?focus=gov&reform=8952&region=us&timePeriod=2024&baseline=2, I receive a white screen, but it's very unclear as to why.

**Comment by MaxGhenis** [comment] 2024-04-12 20:17
I'm getting a "Something went wrong" rather than white https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=8952&region=us&timePeriod=2024&baseline=2

**Comment by anth-volk** [comment] 2024-04-12 20:39
I get this same behavior for #51191 here: https://policyengine.org/us/policy?reform=51191&focus=gov&region=us&timePeriod=2024&baseline=2. This policy seems incredibly important, considering it's very recent - it's for Biden's 2025 budget.

**Comment by daemon-reconfig** [comment] 2024-04-12 20:59
<img width="1680" alt="Screenshot 2024-04-13 at 2 29 23 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/69844188/d9028ae7-604a-4b84-b2c6-c77dd0f7e86c">

it shows a white screen for me as well

**Comment by MaxGhenis** [comment] 2024-04-13 01:33
Now that I'm on a desktop I get white screen as well

**Comment by abhcs** [comment] 2024-04-13 03:27
The cause may be a naming mismatch. The parameter file says `SURVIVING_SPOUSE`:

https://github.com/PolicyEngine/policyengine-us/blob/6f8e29e2e4b43975a1cc3a7fc602d2591e610e14/policyengine_us/parameters/gov/irs/income/bracket.yaml#L156

but the reforms say `WIDOW`. Therefore, parameters such as `gov.irs.income.bracket.thresholds.6.WIDOW` are not found in `metadata` causing further failures.

The renaming happened in https://github.com/PolicyEngine/policyengine-us/pull/4130.

**Comment by MaxGhenis** [comment] 2024-04-13 04:55
Ah yeah shoot. Could we update the policy database to replace instances of WIDOW with SURVIVING_SPOUSE?

**Comment by abhcs** [comment] 2024-04-13 21:12
That can be done -- we can open an issue in pe-api for that (a script will need to be run with db access). This won't help any users who have used the API and have local copies of reforms with `.WIDOW` parameters.

You can consider using a versioning + translation strategy when you change a parameter/variable. So, the reform would include a version number for each parameter that is modified. If an older version of a parameter is found in an existing reform, then the translator would convert it to a new version if possible (should work in trivial cases such as renaming).

**Comment by MaxGhenis** [comment] 2024-04-14 16:09
Filed https://github.com/PolicyEngine/policyengine-api/issues/1400

Agree we should have some strategy for keeping parameter renamings working, as we do with variable aliases.

**Comment by MaxGhenis** [comment] 2024-08-18 00:41
Fixed by #1955

**Closed by MaxGhenis** 2024-08-18 00:41 UTC
Labels: bug
