### ISSUE TITLE
Age field on household calculator displays age to two decimal points, but should display with 0

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#953] opened 2023-12-12 00:05 UTC
<img width="1440" alt="Screen Shot 2023-12-11 at 6 04 13 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/d0a1b416-0072-4c2a-a351-3635c7cf2776">

Would be great to remove the superfluous decimal and post-decimal 0's and to prevent the user from being able to make this anything but a positive integer

**Comment by MaxGhenis** [comment] 2023-12-12 00:15
Duplicate of #928

**Closed by MaxGhenis** 2023-12-12 00:15 UTC
