### ISSUE TITLE
Broken MTR chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#531] opened 2023-05-10 03:28 UTC
https://policyengine.org/us/household?focus=householdOutput.mtr&household=30669

<img width="888" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/b2626c95-ffd6-4211-bfb0-66df79b289f5">

Also happened yesterday with a different reform

**Comment by MaxGhenis** [comment] 2023-05-10 19:28
@lswainemoore and I also just hit some MTR bugs when evaluating the impact of the CalEITC (using a repealed custom baseline):
https://policyengine.org/us/household?focus=householdOutput.mtr&household=30574&region=us&timePeriod=2023&baseline=6416&reform=2
<img width="1917" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/b430b36e-4c67-4b8b-96dd-ab4e383a122b">


And https://policyengine.org/us/household?focus=householdOutput.mtr&household=30688&region=us&timePeriod=2023&baseline=6416&reform=2
<img width="764" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/4af870f6-0021-4058-b0ea-1e39fbae9716">

**Comment by sumitshinde-84** [comment] 2023-05-15 06:00
@MaxGhenis I would be interested in working on this task. Could you please assign it to me and provide additional details about the issue so that I can effectively solve it?

**Comment by MaxGhenis** [comment] 2023-05-15 13:23
Thank you @sumitshinde-84! Though I suspect this is going to be a complex bug that also involves the backend. @nikhilwoodruff could you suggest ways Sumit can help, or assign yourself if if it needs to be you?

**Comment by nikhilwoodruff** [comment] 2023-05-15 14:20
Sure- I think we just need to figure out what the root cause is. I'd suggest trying:
* DevTools in the browser to look at whether the marginal tax rates API request got a 500 error
* If the error is client-side (no 500), then console.log-ing values from the MTR component to see what looks wrong first
* If the error is server-side (500), then using the 'reproduce in python' snippet as a starter to see what the model error is

**Comment by sumitshinde-84** [comment] 2023-05-15 15:51
Thank you so much @MaxGhenis @nikhilwoodruff I would like to give it try .

**Comment by sumitshinde-84** [comment] 2023-05-20 07:31
@MaxGhenis Hey there! I wanted to reach out and kindly request your valuable review on the pull request. Your expertise and feedback mean a lot to me, and I truly appreciate your time and consideration. Thank you so much!

**Comment by MaxGhenis** [comment] 2023-05-23 03:42
Here's another similar instance: Creating a single parent of one 4yo child in California, with $24k rent, $12k childcare, and $600 broadband, shows functional net income and MTR charts when first making them, but then refreshing the page makes it break.

https://policyengine.org/us/household?focus=householdOutput.mtr&household=30975

https://www.loom.com/share/a16f95bebe3847bf9715c81b5049aeeb

**Comment by nikhilwoodruff** [comment] 2023-05-23 08:49
OK now fixed, so closing.

**Closed by nikhilwoodruff** 2023-05-23 08:49 UTC
Labels: bug
