### ISSUE TITLE
Changing the federal minimum wage has no impact

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1178] opened 2024-01-12 16:47 UTC
If I change the [federal minimum wage](https://policyengine.org/us/policy?focus=gov.dol.minimum_wage&reform=39047&region=us&timePeriod=2024&baseline=2) from `$7.25` to `$50` and calculate the economic impact, PolicyEngine tells me that the reform will have [no impact on poverty and other metrics](https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=43785&region=us&timePeriod=2024&baseline=2).

This seems counter-intuitive because changing the wage should have some impact. PolicyEngine reports no impacts even when I change the minimum wage to `$500`. Is this expected behavior?

**Comment by MaxGhenis** [comment] 2024-01-12 17:37
Duplicate of #816

See that issue for an explanation

**Closed by MaxGhenis** 2024-01-12 17:37 UTC
Labels: question
