### ISSUE TITLE
Generated Python code quotes scale parameter values

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#1974] opened 2024-08-16 12:54 UTC
The [generated code](https://policyengine.org/us/household?reform=63519&focus=householdOutput.pythonReproducibility&region=enhanced_us&timePeriod=2024&baseline=2&household=46590) should not quotation marks around `3600` and `3000`

![image](https://github.com/user-attachments/assets/fb768153-8b15-40ce-ad18-900a5cba3b17)

**Comment by anth-volk** [comment] 2024-08-21 18:12
![](https://github.trello.services/images/mini-trello-icon.png) [Generated Python code quotes scale parameter values](https://trello.com/c/UGayYD2g/12-generated-python-code-quotes-scale-parameter-values)

**Comment by anth-volk** [comment] 2024-09-02 20:31
@PavelMakarchuk How significant an impact does this have when actually running the output Python code locally? Is it fully breaking, or are these values forced into number types when run? Just curious.

**Comment by anth-volk** [comment] 2024-09-02 20:33
This issue almost certainly emerges from the API, not the app. When accessing the sample policy given above in the issue at https://api.policyengine.org/us/policy/63519, the values stored in the policy record itself are stored as strings, not numbers, making debugging this likely a bit more challenging.

**Comment by anth-volk** [comment] 2024-09-02 20:48
When manually selecting these same provisions in the app over the same time periods, the API correctly returns numeric-type values, meaning that the Reproduce in Python section correctly displays values:

<img width="679" alt="Screen Shot 2024-09-02 at 10 47 55 PM" src="https://github.com/user-attachments/assets/f2f6f4a5-cca0-4ef7-8022-38210b1de749">

**Comment by PavelMakarchuk** [comment] 2024-09-09 12:56
> When manually selecting these same provisions in the app over the same time periods, the API correctly returns numeric-type values, meaning that the Reproduce in Python section correctly displays values:
> 
> <img alt="Screen Shot 2024-09-02 at 10 47 55 PM" width="679" src="https://private-user-images.githubusercontent.com/14987227/363788713-f2f6f4a5-cca0-4ef7-8022-38210b1de749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODY3ODgsIm5iZiI6MTcyNTg4NjQ4OCwicGF0aCI6Ii8xNDk4NzIyNy8zNjM3ODg3MTMtZjJmNmY0YTUtY2NhMC00ZWY3LTgwMjItMzgyMTBiMWRlNzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZWMzY2VmZWM0ZDM1Zjc4ZDk1OGI4ZTg0ZGRlMmJlZGNhNDJkYWZmYWY0MDQyOWUxNWQ1MjhlMGNhNjQ4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQCN86jJ5ka1OEeZs1JeNTTvj2-Vn3EEPHSQOFwPkHM">

In the Microsim and Household reproduce in python sections?

**Comment by anth-volk** [comment] 2024-09-09 13:37
> > When manually selecting these same provisions in the app over the same time periods, the API correctly returns numeric-type values, meaning that the Reproduce in Python section correctly displays values:
> > <img alt="Screen Shot 2024-09-02 at 10 47 55 PM" width="679" src="https://private-user-images.githubusercontent.com/14987227/363788713-f2f6f4a5-cca0-4ef7-8022-38210b1de749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODY3ODgsIm5iZiI6MTcyNTg4NjQ4OCwicGF0aCI6Ii8xNDk4NzIyNy8zNjM3ODg3MTMtZjJmNmY0YTUtY2NhMC00ZWY3LTgwMjItMzgyMTBiMWRlNzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZWMzY2VmZWM0ZDM1Zjc4ZDk1OGI4ZTg0ZGRlMmJlZGNhNDJkYWZmYWY0MDQyOWUxNWQ1MjhlMGNhNjQ4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQCN86jJ5ka1OEeZs1JeNTTvj2-Vn3EEPHSQOFwPkHM">
> 
> In the Microsim and Household reproduce in python sections?

Correct. When I run the household link that you provided, I do see the quotation marks. However, when I duplicate the household by adding the same provisions to a new household, the values have no quotation marks. The problem was likely some sort of back-end bug, but I'm unable to recreate that back-end bug, and am unsure where it would originate from.

**Comment by anth-volk** [comment] 2024-10-04 17:14
@PavelMakarchuk Have there been any households that have been created with the quotation marks since you opened this?

If not, I think this is a fluke and this issue can be closed.

**Comment by anth-volk** [comment] 2024-10-05 21:36
Thanks! Closing.

**Closed by anth-volk** 2024-10-05 21:36 UTC
Labels: bug
