### ISSUE TITLE
"You are here" point on earnings chart isn't on the line

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#952] opened 2023-12-11 23:43 UTC
<img width="712" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/3388c760-7e8b-4991-bee8-0d664b624590">

https://policyengine.org/us/household?focus=householdOutput.earnings&household=37295

Also with some (but not all) other programs:
<img width="685" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/20010338-34f8-45cf-89fe-6c0723211c99">

Happening in the [UK](https://policyengine.org/uk/household?focus=householdOutput.earnings&household=37300) too:
<img width="770" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/0859060c-b2b2-4bf3-bed1-48b12916640a">

[MTR](https://policyengine.org/us/household?focus=householdOutput.mtr&household=37295) looks ok:
<img width="754" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/47891cc5-13d8-4fc7-bdd0-354005f117d7">

**Comment by anth-volk** [comment] 2023-12-12 00:01
Weirdly enough, when I access the links you sent, it's not reproducing for me. I'll try creating a new household and see if it reappears.

**Comment by anth-volk** [comment] 2023-12-12 01:47
I've spent some time digging into this, but I think I'll have to continue tomorrow. It appears the problem stems from the following:

* The "you are here" dot is derived from the API's `get_household_under_policy` endpoint, which for the UK example above, indicates that the household's net income is 1,239 pounds
* The line is derived from the API's `get_calculate` endpoint, with the flag for adding yearly variables set to true. This generates an array where the household's net income variance at 0 is 1,398 pounds

I'm not yet sure why that is. I'll have to dig more into this by running the API locally and seeing if the issue stems from the `get_calculate` endpoint and its optional flag to add yearly variables. I'm also curious if it's possible that a bug in core could be causing this, since it's across country packages, relatively recent, and doesn't appear to be a visual or API data accessing error.

**Comment by anth-volk** [comment] 2023-12-13 00:01
An update on this: the flag adding yearly variables is not the cause of the issue. The issue also doesn't appear to be the API-side code from the `country.py` file, as nothing has been edited in there for quite some time. Removing caching from the `get-calculate` endpoint also changes nothing. 

I'm wondering if the issue doesn't stem from one of the following: 
1. Some sort of change to `policyengine-core` that alters the calculations
2. A locally cached version of the household that is accessed as part of the `get_household_under_policy` endpoint, as I've had some difficulty manually creating the household locally, then placing it under the default policy

**Comment by anth-volk** [comment] 2023-12-13 00:07
Strike that, I don't think it's #2, as I finally successfully created the household locally, then accessed the `get_household_under_policy` endpoint and received the expected £1239 for `household_net_income`, while still getting an output from `get_calculate` that sets the graph line starting at £1398. @nikhilwoodruff Can you imagine any changes to `policyengine-core` that might have created this disparity?

**Comment by anth-volk** [comment] 2023-12-13 16:30
Nikhil has found that for the UK example, an issue with a stochastic model of the TV licence fee has led to the disparity, where the point on the line is being simulated without the TV licence fee and the line is being simulated with it.

**Comment by anth-volk** [comment] 2023-12-13 16:38
Issue appears to be the random function in `formulas.py` in `policyengine-core`, as the function does not simulate random variables for the line (any simulation with axes)

**Comment by anth-volk** [comment] 2023-12-13 21:41
Since this bug is definitely caused by `policyengine-core`, I'm going to close this, then open a new one there with a link to all of this information.

**Comment by anth-volk** [comment] 2023-12-14 22:18
Reopening due to errors at https://policyengine.org/us/household?focus=householdOutput.earnings&household=37549

**Comment by anth-volk** [comment] 2023-12-14 22:19
![image](https://github.com/PolicyEngine/policyengine-app/assets/14987227/d73d0168-7f41-417f-ab87-962bc105de5e)

**Comment by anth-volk** [comment] 2023-12-14 22:36
Was able to reproduce by first inputting most variables, but leaving out employment income, allowing the app to calculate household output, then inputting employment income

**Comment by anth-volk** [comment] 2023-12-14 22:51
The variable editor component checks for changes to any piece of information in the household, and if it occurs, updates via the `calculate` endpoint; meanwhile, the `get_household_under_policy` endpoint is only invoked on first load or if the household ID, policy ID, or country ID are changed - once the household’s been assigned an ID, there won’t be any call to that endpoint unless the page is refreshed. This means that even though a household might change a variable, the app is stuck with stale "household under policy" simulation data.

**Comment by anth-volk** [comment] 2023-12-14 23:04
Interestingly, updating children or marital status will force a reload and place the dot properly, but market income, for example, will not

**Comment by anth-volk** [comment] 2023-12-14 23:19
I take that back, at times it does and at times it doesn't

**Comment by anth-volk** [comment] 2023-12-14 23:25
This can be reproduced by changing a variable and typing in the value quickly, then clicking off to another screen - the app creates a new household every time there's a change in input, so it appears that a quick change with an input with many digits is unable to complete building each new household before the output page mounts, while the right-hand sidebar does not mount or unmount, allowing it to finish calculations?

**Comment by anth-volk** [comment] 2023-12-14 23:37
It appears that the effect hook in `HouseholdPage` doesn't correctly order the requests made to it, causing very rapid inputs to resolve out of order

**Comment by anth-volk** [comment] 2023-12-15 02:28
This issue is caused by our use of the `formatter` parameter in the `VariableEditor` component

**Comment by anth-volk** [comment] 2023-12-15 03:08
Update: this is actually caused by the entire implementation of antd's `InputNumber` component. In a nutshell, the old PolicyEngine-built `InputField` component had an `onChange` handler that only submitted and created a new household with a new ID on perceived submit (when someone exited the input, used a key to exit it, or pressed Enter). Our implementation of antd's component, meanwhile, creates a new household on every change, and if these updates happen too quickly, this causes the requisite back-end requests to become poorly sequenced, sometimes causing the `get_household_under_policy` calls necessary to place the dot on the chart to be incorrect by one or more orders of magnitude.

Will be reverting to the PolicyEngine-built `InputField`, then hopefully reworking the antd implementation to function properly.

**Comment by abhcs** [comment] 2023-12-15 03:18
If the wrong cases are infrequent or corner cases, it may be better to just fix the handler of `InputNumber`. See #946.

**Comment by anth-volk** [comment] 2023-12-15 03:22
@abhcs The wrong cases are actually pretty frequent. That said, I completely agree. I'm only opening a PR to revert to `InputField` temporarily, as it does function similarly to how I think #946 envisions, it's just not the most aesthetically pleasing. I think this bug is breaking enough to warrant the reversion, even if temporary.

**Closed** 2023-12-15 03:34 UTC
Labels: bug

**Comment by MaxGhenis** [comment] 2023-12-15 03:48
Success! Thank you @anth-volk!
<img width="794" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/fad6d8a1-0ab5-4221-b142-f7124fb26d56">
https://policyengine.org/us/household?focus=householdOutput.earnings&household=37788
