### ISSUE TITLE
The "calculate impact" button is disabled when comparing the baseline against a reform

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#1937] opened 2024-07-29 23:39 UTC
The only way to run the reform is to run the reform agains baseline and then flip the impacts 

https://github.com/user-attachments/assets/ee6f25ad-113a-4650-9576-c5709d3ebbd3

**Comment by MaxGhenis** [comment] 2024-07-30 00:24
Duplicate of #1859 (see workaround there)

**Closed by MaxGhenis** 2024-07-30 00:24 UTC
